name: suorotsav_2026
description: "Manthan 2026 — College Tech Fest Website"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/soumit.png
    - assets/sayantani.png
    - assets/logo/
    - assets/events/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_white.png"
  web:
    generate: true
    image_path: "assets/logo/logo_white.png"
    background_color: "#0A0E1A"
    theme_color: "#0A0E1A"
  windows:
    generate: true
    image_path: "assets/logo/logo_white.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo/logo_white.png"
